### ISSUE TITLE
ban-wildcard-imports?

### ISSUE THREAD

**Issue by nmichlo** [adamchainz/flake8-tidy-imports#435]
### Description

Great project!

I was wondering if there would be any interest in adding the ability to bad wildcard imports.

So for example:
`from my_module import *` would be disallowed, but `from my_module import my_function` would be allowed.

Reason is that this may help with finding usages, and preventing name conflicts in repos.

**PEP8**:
> Wildcard imports (from <module> import *) should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools. There is one defensible use case for a wildcard import, which is to republish an internal interface as part of a public API (for example, overwriting a pure Python implementation of an interface with the definitions from an optional accelerator module and exactly which definitions will be overwritten isn’t known in advance).

https://peps.python.org/pep-0008/#imports

- based on this, maybe an option for allowing wildcards in `__import__.py` files can be an option too.

- maybe with an optional whitelist, so you can allow certain packages like `typing` (personally wouldn't use this, but seems to be common)

**Comment by adamchainz** [comment]
Flake8's [F403 error code](https://flake8.pycqa.org/en/latest/user/error-codes.html) already fails any `from _ import *`. I find that's sufficient, with targeted `# noqa:F403` comments where `import *` is necessary.

> * based on this, maybe an option for allowing wildcards in `__import__.py` files can be an option too.

Do you mean `__init__.py` ? You can already disable F403 in such files with this flake8 config:

```
per-file-ignores =
    */__init__.py:F403
```

Since flake8 already supports this, I'm gonna close the issue, but do respond if there's more you need.

**Comment by nmichlo** [comment]
Oh! thank you! I completely missed this.
